### ISSUE TITLE
download lyrics

### ISSUE THREAD

**Issue by trmendes** [shkcodes/Lyrically#26]
Hi. Every time I click on download lyrics it will show me a message asking me if I want to save xxxx lyrics and I always hit yes. So far the app never downloaded any of those xxxx lyrics to my phone.

**Comment by shkcodes** [comment]
Can you check if the Lyrically folder is present in your internal storage? Did you grant the proper permissions?

**Comment by trmendes** [comment]
Yes...it is present and I gave the app the permission.

**Comment by shkcodes** [comment]
I'll look into this tomorrow after I return from my exam.

Will message you if I find something.

**Comment by shkcodes** [comment]
Did you get the update? It should work now.

**Comment by shkcodes** [comment]
Wait I didn't mean to send this mail to you. My bad!

**Comment by trmendes** [comment]
Hey @shkcodes. Sorry for the late reply. I was just trying the last version from Fdroid and still not working. When I click on download lyrics the app shows me a dialog saying it will download the lyrica for X songs and after I click yes nothing seens to happen. No progress bar, no downloading counting, no message, nothing...it just goes back to the main activity. The app has access to write/read the file system and I'm using the LineageOs nightly version.

**Comment by shkcodes** [comment]
What phone do you have? Can you see if Lyrically folder is present in your
internal storage? If not, create it and try again.

On Jun 6, 2017 7:59 PM, "Thiago M" <notifications@github.com> wrote:

Hey @shkcodes <https://github.com/shkcodes>. Sorry for the late reply. I
was just trying the last version from Fdroid and still not working. When I
click on download lyrics the app shows me a dialog saying it will download
the lyrica for X songs and after I click yes nothing seens to happen. No
progress bar, no downloading counting, no message, nothing...it just goes
back to the main activity. The app has access to write/read the file system
and I'm using the LineageOs nightly version.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/shkcodes/Lyrically/issues/26#issuecomment-306487912>,
or mute the thread

**Comment by trmendes** [comment]
@shkcodes What is the Lyrically folder name?

**Comment by trmendes** [comment]
There is a Lyrically directory at my internal memory and I have a Samsung s4 running lineosage 14.1 nightly (last version)

**Comment by shkcodes** [comment]
And does it contain text files with lyrics?

**Comment by trmendes** [comment]
It is empty

**Comment by shkcodes** [comment]
I seems like a Samsung specific bug. I will look into it if I can. But can't make any promises.

**Comment by trmendes** [comment]
No worries! Again...I'm not using the oficial Samsung rom. I'm using LineAgeOs...

**Comment by shkcodes** [comment]
Can you try the latest version?

**Comment by trmendes** [comment]
I'm using the last version from fdroid which is 0.51

**Comment by shkcodes** [comment]
I uploaded a new version today on Github(0.52).

**Comment by trmendes** [comment]
@shkcodes it is working now :)....the only issue is that before it would show me the right ammount of music saying "Lyrics to download: 5400" and now it says something like "Lyrcis to Download: 900"....but it is downloading them :D...now I can see the files inside the folder

**Comment by Hossainbd2018** [comment]
Hey @shkcodes you can help me? When I downloaded song lyrics from the lyrically, the application is error, and show the display unfortunately, lyrically has stopped. How can i solve this?

**Comment by shkcodes** [comment]
Hey @Hossainbd2018 did you grant the storage permission to Lyrically? What phone and OS version are you using? Also, where exactly did it crash; while showing the lyrics or while downloading them using the button inside the app? Please provide more details.

**Comment by Hossainbd2018** [comment]
Thanks, it worked.
